import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface SelectedOpenApiOperation {
  readonly key: string;
  readonly method: string;
  readonly path: string;
  readonly operationId: string;
}

export interface ExtractedOpenApiOperation extends SelectedOpenApiOperation {
  readonly summary?: string;
  readonly parameters: readonly ExtractedParameter[];
  readonly requestBody?: ExtractedRequestBody;
  readonly responses: Readonly<Record<string, ExtractedResponse>>;
}

export interface ExtractedParameter {
  readonly name: string;
  readonly in: 'path' | 'query';
  readonly required: boolean;
  readonly schema: CompactJsonSchema;
  readonly description?: string;
}

export interface ExtractedRequestBody {
  readonly required: boolean;
  readonly contentType: 'application/json';
  readonly schema: CompactJsonSchema;
}

export interface ExtractedResponse {
  readonly description: string;
  readonly schema?: CompactJsonSchema;
}

export type CompactJsonSchema = Readonly<Record<string, unknown>>;

interface OpenApiDocument {
  readonly openapi?: string;
  readonly info?: { readonly title?: string; readonly version?: string };
  readonly paths?: Record<string, PathItem>;
  readonly components?: { readonly schemas?: Record<string, unknown> };
}

type PathItem = Record<string, OperationObject | unknown>;
type OperationObject = Record<string, unknown> & {
  readonly operationId?: string;
  readonly summary?: string;
  readonly parameters?: readonly unknown[];
  readonly requestBody?: unknown;
  readonly responses?: Record<string, unknown>;
};

const HTTP_METHODS = new Set(['get', 'put', 'post', 'delete', 'patch', 'options', 'head', 'trace']);
const DEFAULT_SOURCE = 'src/remnawave-api/openapi/remnawave-openapi-2.7.4.json';
const DEFAULT_OUTPUT = 'src/remnawave-api/generated/operations.ts';

export const SELECTED_OPENAPI_OPERATIONS = [
  {
    key: 'users.create_user',
    method: 'post',
    path: '/api/users',
    operationId: 'UsersController_createUser',
  },
  {
    key: 'users.list',
    method: 'get',
    path: '/api/users',
    operationId: 'UsersController_getAllUsers',
  },
  {
    key: 'users.get_by_uuid',
    method: 'get',
    path: '/api/users/{uuid}',
    operationId: 'UsersController_getUserByUuid',
  },
  {
    key: 'system.get_stats',
    method: 'get',
    path: '/api/system/stats',
    operationId: 'SystemController_getStats',
  },
] as const satisfies readonly SelectedOpenApiOperation[];

export class UnsupportedSchemaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UnsupportedSchemaError';
  }
}

export function extractOpenApiSnapshot(
  document: OpenApiDocument,
  selectedOperations: readonly SelectedOpenApiOperation[] = SELECTED_OPENAPI_OPERATIONS,
): { readonly metadata: Record<string, unknown>; readonly operations: readonly ExtractedOpenApiOperation[] } {
  if (!document.paths || typeof document.paths !== 'object') {
    throw new Error('OpenAPI document is missing paths.');
  }

  return {
    metadata: sortObject({
      openapi: document.openapi,
      title: document.info?.title,
      version: document.info?.version,
      extractedAt: 'static',
      source: 'remnawave-openapi-2.7.4.json',
    }),
    operations: selectedOperations.map((selection) => extractOperation(document, selection)),
  };
}

export function readOpenApiSnapshot(path: string): OpenApiDocument {
  return JSON.parse(readFileSync(path, 'utf8')) as OpenApiDocument;
}

export function writeGeneratedOperationsModule(extracted: ReturnType<typeof extractOpenApiSnapshot>, outputPath: string): void {
  const body = stableStringify(extracted);
  const content = `// Generated by scripts/extract-remnawave-openapi.ts. Do not edit by hand.\n\nexport const REMNAWAVE_OPENAPI_EXTRACT = (${body.trimEnd()}) as const;\n\nexport type RemnawaveOpenApiExtract = typeof REMNAWAVE_OPENAPI_EXTRACT;\nexport type RemnawaveOpenApiOperation = RemnawaveOpenApiExtract['operations'][number];\n`;
  writeFileSync(outputPath, content);
}

function extractOperation(document: OpenApiDocument, selection: SelectedOpenApiOperation): ExtractedOpenApiOperation {
  const pathItem = document.paths?.[selection.path];
  if (!isRecord(pathItem)) {
    throw new Error(`Selected OpenAPI path not found: ${selection.method.toUpperCase()} ${selection.path}.`);
  }

  const method = selection.method.toLowerCase();
  if (!HTTP_METHODS.has(method)) {
    throw new Error(`Unsupported HTTP method in selection ${selection.key}: ${selection.method}.`);
  }

  const operation = pathItem[method];
  if (!isRecord(operation)) {
    throw new Error(`Selected OpenAPI operation not found: ${selection.method.toUpperCase()} ${selection.path}.`);
  }

  if (operation.operationId !== selection.operationId) {
    throw new Error(
      `Selected OpenAPI operationId mismatch for ${selection.method.toUpperCase()} ${selection.path}: expected ${selection.operationId}, got ${String(operation.operationId)}.`,
    );
  }

  return sortObject({
    key: selection.key,
    method,
    path: selection.path,
    operationId: selection.operationId,
    summary: typeof operation.summary === 'string' ? operation.summary : undefined,
    parameters: extractParameters(document, operation.parameters),
    requestBody: extractRequestBody(document, operation.requestBody),
    responses: extractResponses(document, operation.responses),
  }) as unknown as ExtractedOpenApiOperation;
}

function extractParameters(document: OpenApiDocument, parameters: unknown): readonly ExtractedParameter[] {
  if (parameters === undefined) {
    return [];
  }
  if (!Array.isArray(parameters)) {
    throw new Error('Operation parameters must be an array when present.');
  }

  return parameters.map((parameter, index) => {
    const resolved = resolveReference(document, parameter, `parameters[${index}]`, []);
    if (!isRecord(resolved)) {
      throw new Error(`Parameter at index ${index} must be an object.`);
    }
    if (resolved.in !== 'path' && resolved.in !== 'query') {
      throw new UnsupportedSchemaError(`Unsupported parameter location at parameters[${index}]: ${String(resolved.in)}.`);
    }
    if (typeof resolved.name !== 'string') {
      throw new Error(`Parameter at index ${index} is missing name.`);
    }
    if (!isRecord(resolved.schema)) {
      throw new Error(`Parameter ${resolved.name} is missing schema.`);
    }

    return sortObject({
      name: resolved.name,
      in: resolved.in,
      required: resolved.required === true,
      description: typeof resolved.description === 'string' ? resolved.description : undefined,
      schema: compactSchema(document, resolved.schema, `parameter ${resolved.name}`, []),
    }) as unknown as ExtractedParameter;
  });
}

function extractRequestBody(document: OpenApiDocument, requestBody: unknown): ExtractedRequestBody | undefined {
  if (requestBody === undefined) {
    return undefined;
  }

  const resolved = resolveReference(document, requestBody, 'requestBody', []);
  if (!isRecord(resolved)) {
    throw new Error('requestBody must be an object.');
  }

  const mediaType = getJsonMediaType(resolved, 'requestBody');
  if (!isRecord(mediaType.schema)) {
    throw new Error('JSON requestBody is missing schema.');
  }

  return sortObject({
    required: resolved.required === true,
    contentType: 'application/json',
    schema: compactSchema(document, mediaType.schema, 'requestBody', []),
  }) as unknown as ExtractedRequestBody;
}

function extractResponses(document: OpenApiDocument, responses: unknown): Readonly<Record<string, ExtractedResponse>> {
  if (!isRecord(responses)) {
    throw new Error('Operation responses must be an object.');
  }

  const extracted: Record<string, ExtractedResponse> = {};
  for (const status of Object.keys(responses).sort()) {
    const resolved = resolveReference(document, responses[status], `responses.${status}`, []);
    if (!isRecord(resolved)) {
      throw new Error(`Response ${status} must be an object.`);
    }
    const mediaType = getOptionalJsonMediaType(resolved);
    extracted[status] = sortObject({
      description: typeof resolved.description === 'string' ? resolved.description : '',
      schema: isRecord(mediaType?.schema) ? compactSchema(document, mediaType.schema, `responses.${status}`, []) : undefined,
    }) as unknown as ExtractedResponse;
  }

  return sortObject(extracted) as Readonly<Record<string, ExtractedResponse>>;
}

function compactSchema(document: OpenApiDocument, schema: unknown, location: string, stack: readonly string[]): CompactJsonSchema {
  const resolved = resolveReference(document, schema, location, stack);
  if (!isRecord(resolved)) {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: expected object.`);
  }

  if (Object.keys(resolved).length === 0) {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: empty schemas are not allowed.`);
  }

  if ('not' in resolved) {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: not is not supported.`);
  }
  if ('discriminator' in resolved) {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: discriminator is not supported.`);
  }

  const nullable = resolved.nullable === true;
  const withoutNullable = { ...resolved };
  delete withoutNullable.nullable;
  const compact = compactNonNullableSchema(document, withoutNullable, location, stack);

  if (!nullable) {
    return compact;
  }

  return sortObject({ anyOf: [compact, { type: 'null' }] });
}

function compactNonNullableSchema(
  document: OpenApiDocument,
  schema: Record<string, unknown>,
  location: string,
  stack: readonly string[],
): CompactJsonSchema {
  const combiners = ['allOf', 'oneOf', 'anyOf'] as const;
  for (const combiner of combiners) {
    if (combiner in schema) {
      if (!Array.isArray(schema[combiner]) || schema[combiner].length === 0) {
        throw new UnsupportedSchemaError(`Unsupported schema at ${location}: ${combiner} must be a non-empty array.`);
      }
      return sortObject({
        ...copySchemaAnnotations(schema),
        [combiner]: (schema[combiner] as readonly unknown[]).map((item, index) =>
          compactSchema(document, item, `${location}.${combiner}[${index}]`, stack),
        ),
      });
    }
  }

  const type = schema.type ?? (isRecord(schema.properties) ? 'object' : undefined);
  if (typeof type !== 'string') {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: missing explicit type.`);
  }

  switch (type) {
    case 'string':
    case 'integer':
    case 'number':
    case 'boolean':
      return sortObject({ ...copySchemaAnnotations(schema), type, ...copyScalarConstraints(schema) });
    case 'array':
      if (!isRecord(schema.items)) {
        throw new UnsupportedSchemaError(`Unsupported schema at ${location}: array schema is missing object items.`);
      }
      return sortObject({
        ...copySchemaAnnotations(schema),
        type,
        ...copyArrayConstraints(schema),
        items: compactSchema(document, schema.items, `${location}.items`, stack),
      });
    case 'object':
      return compactObjectSchema(document, schema, location, stack);
    default:
      throw new UnsupportedSchemaError(`Unsupported schema at ${location}: unsupported type ${type}.`);
  }
}

function compactObjectSchema(
  document: OpenApiDocument,
  schema: Record<string, unknown>,
  location: string,
  stack: readonly string[],
): CompactJsonSchema {
  const properties = isRecord(schema.properties) ? schema.properties : undefined;
  const compactProperties: Record<string, CompactJsonSchema> = {};
  if (properties) {
    for (const propertyName of Object.keys(properties).sort()) {
      compactProperties[propertyName] = compactSchema(document, properties[propertyName], `${location}.properties.${propertyName}`, stack);
    }
  }

  const additionalProperties = schema.additionalProperties;
  let compactAdditionalProperties: boolean | CompactJsonSchema | undefined;
  if (additionalProperties === undefined) {
    compactAdditionalProperties = undefined;
  } else if (typeof additionalProperties === 'boolean') {
    compactAdditionalProperties = additionalProperties;
  } else if (isRecord(additionalProperties)) {
    compactAdditionalProperties = compactSchema(document, additionalProperties, `${location}.additionalProperties`, stack);
  } else {
    throw new UnsupportedSchemaError(`Unsupported schema at ${location}: additionalProperties must be boolean or schema object.`);
  }

  return sortObject({
    ...copySchemaAnnotations(schema),
    type: 'object',
    additionalProperties: compactAdditionalProperties,
    properties: Object.keys(compactProperties).length > 0 ? sortObject(compactProperties) : undefined,
    required: normalizeStringArray(schema.required, `${location}.required`),
  });
}

function resolveReference(document: OpenApiDocument, value: unknown, location: string, stack: readonly string[]): unknown {
  if (!isRecord(value) || typeof value.$ref !== 'string') {
    return value;
  }

  const ref = value.$ref;
  if (!ref.startsWith('#/')) {
    throw new UnsupportedSchemaError(`Unsupported reference at ${location}: only local refs are supported (${ref}).`);
  }
  if (stack.includes(ref)) {
    throw new UnsupportedSchemaError(`Unsupported reference cycle at ${location}: ${[...stack, ref].join(' -> ')}.`);
  }

  const resolved = ref
    .slice(2)
    .split('/')
    .map((part) => part.replace(/~1/g, '/').replace(/~0/g, '~'))
    .reduce<unknown>((current, part) => (isRecord(current) ? current[part] : undefined), document as unknown);

  if (resolved === undefined) {
    throw new Error(`Unable to resolve reference at ${location}: ${ref}.`);
  }

  const siblingKeys = Object.keys(value).filter((key) => key !== '$ref');
  if (siblingKeys.length > 0) {
    throw new UnsupportedSchemaError(`Unsupported reference at ${location}: $ref siblings are not supported (${siblingKeys.join(', ')}).`);
  }

  return resolveReference(document, resolved, ref, [...stack, ref]);
}

function getJsonMediaType(container: Record<string, unknown>, location: string): Record<string, unknown> {
  const mediaType = getOptionalJsonMediaType(container);
  if (!mediaType) {
    throw new UnsupportedSchemaError(`Unsupported ${location}: application/json content is required.`);
  }
  return mediaType;
}

function getOptionalJsonMediaType(container: Record<string, unknown>): Record<string, unknown> | undefined {
  const content = container.content;
  if (!isRecord(content)) {
    return undefined;
  }
  const mediaType = content['application/json'];
  return isRecord(mediaType) ? mediaType : undefined;
}

function copySchemaAnnotations(schema: Record<string, unknown>): Record<string, unknown> {
  return pick(schema, ['description', 'format', 'default', 'example', 'deprecated', 'readOnly', 'writeOnly', 'enum']);
}

function copyScalarConstraints(schema: Record<string, unknown>): Record<string, unknown> {
  return pick(schema, [
    'minimum',
    'maximum',
    'exclusiveMinimum',
    'exclusiveMaximum',
    'minLength',
    'maxLength',
    'pattern',
    'multipleOf',
  ]);
}

function copyArrayConstraints(schema: Record<string, unknown>): Record<string, unknown> {
  return pick(schema, ['minItems', 'maxItems', 'uniqueItems']);
}

function pick(source: Record<string, unknown>, keys: readonly string[]): Record<string, unknown> {
  const picked: Record<string, unknown> = {};
  for (const key of keys) {
    if (source[key] !== undefined) {
      picked[key] = source[key];
    }
  }
  return picked;
}

function normalizeStringArray(value: unknown, location: string): readonly string[] | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    throw new Error(`${location} must be an array of strings.`);
  }
  return [...value].sort();
}

function sortObject<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((item) => sortObject(item)) as T;
  }
  if (!isRecord(value)) {
    return value;
  }

  const output: Record<string, unknown> = {};
  for (const key of Object.keys(value).sort()) {
    const item = value[key];
    if (item !== undefined) {
      output[key] = sortObject(item);
    }
  }
  return output as T;
}

function stableStringify(value: unknown): string {
  return `${JSON.stringify(sortObject(value), null, 2)}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function runCli(): void {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const source = resolve(root, process.argv[2] ?? DEFAULT_SOURCE);
  const output = resolve(root, process.argv[3] ?? DEFAULT_OUTPUT);
  const document = readOpenApiSnapshot(source);
  const extracted = extractOpenApiSnapshot(document);
  writeGeneratedOperationsModule(extracted, output);
  process.stdout.write(`Extracted ${extracted.operations.length} Remnawave OpenAPI operations to ${output}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli();
}
